### ISSUE TITLE
util._extend been deprecated use Object.assign() instead

### ISSUE THREAD

**Issue by cryst10** [carsondarling/node-http-error#4]
Since util._extend is deprecated and should not be used in new code. JavaScript comes with very similar built-in functionality through Object.assign().

https://nodejs.org/api/util.html#util_util_extend_target_source

**Comment by carsondarling** [comment]
@cryst10 I'll take a look at this at some point this week. If you want to propose a PR, that would be great.

**Comment by carsondarling** [comment]
Closing with #5

**Comment by carsondarling** [comment]
These changes are now available as [`node-http-error@2.0.0`](https://www.npmjs.com/package/node-http-error)
